# Generated by Django 2.2.10 on 2020-03-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20200228_1238'),
        ('currency', '0002_auto_20200303_2113'),
    ]

    operations = [
    ]
